### ISSUE TITLE
Absolute path inside a module.

### ISSUE THREAD

**Issue by xEnVrE** [qwattash/anrem#8]
Sometimes cli tools require absolute paths (e.g. VBoxManage while creating a new vm and specifying the base folder path).

Is it possible to have an 'anrem-current-path' like function to get the absolute path inside a module?

Hint: an absolute path could be easily obtained using 

readlink -f (dir relative to the working directory).

**Comment by qwattash** [comment]
Use make's function $(abspath $(current_path)) seems a decent solution to
me, let me know.

2014-09-02 4:24 GMT+02:00 xEnVrE notifications@github.com:

**Comment by xEnVrE** [comment]
It works as should. Closing now.
